// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rent_a_Car_.Net.DAL;

#nullable disable

namespace Rent_a_Car_.Net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240307213627_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeaderDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Desc = "Rent A Car şirkəti yeni yaranmasına baxmayaraq, ölkədə ən böyük avtomobil qarajına sahibdir. Bizim bütün avtomobillərimiz  bütün standartlara cavab verən, ekoloji tələblərə riayət edən yeni avtomobillərdir. Bizim şirkət avtomobil icarəsi bazarına yeni daxil olduğu üçün sərfəli qiymətlərlə digər şirkətləri üstələyir. Kirayə maşın bazarında çox şirkətin olmasına baxmayaraq keyfiyyətli və təhlükəsiz şirkət azlıq təşkil edir.",
                            HeaderDesc = "Əziz şəhərimizin qonaqları sizi “Rent A Car” şirkəti olaraq salamlayırıq.",
                            ImageUrl = "hero_2.jpg",
                            Title = "BİZ KİMİK"
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Bio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "+994 77 710 19 98",
                            Email = "arzuem@code.edu.az",
                            ImageUrl = "logo.png",
                            Location = "Nizami küçəsi 203B, AF Business House, 2-ci mərtəbə, Baku 1000, Azerbaijan",
                            WorkTime = "Bazar ertəsi-Şənbə 9:00pm - 5:00pm Bazar:Bağlıdır"
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(5920),
                            ImageUrl = "mercedes.png",
                            Name = "Mercedes",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6004),
                            ImageUrl = "hyundai.png",
                            Name = "Hyundai",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6023),
                            ImageUrl = "toyota.png",
                            Name = "Toyota",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6040),
                            ImageUrl = "bmw.png",
                            Name = "BMW",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6058),
                            ImageUrl = "nissan.png",
                            Name = "Nissan",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6079),
                            ImageUrl = "mitsubishi.png",
                            Name = "Mitsubishi",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6163),
                            ImageUrl = "kia.png",
                            Name = "Kia",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6180),
                            ImageUrl = "chevrolet.png",
                            Name = "Chevrolet",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6198),
                            ImageUrl = "lexus.png",
                            Name = "Lexus",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6220),
                            ImageUrl = "tesla.png",
                            Name = "Tesla",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DailyPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 4,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6384),
                            DailyPrice = 250.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "M5",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6411),
                            DailyPrice = 120.0,
                            FuelType = 2,
                            ModelYear = 2015,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 8,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6428),
                            DailyPrice = 50.0,
                            FuelType = 3,
                            ModelYear = 2013,
                            Name = "Aveo",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6443),
                            DailyPrice = 50.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Accent",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6461),
                            DailyPrice = 85.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Azera",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6482),
                            DailyPrice = 55.0,
                            FuelType = 1,
                            ModelYear = 2015,
                            Name = "Elantra",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6496),
                            DailyPrice = 140.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "H1",
                            PassengerCount = 9,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6512),
                            DailyPrice = 65.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Ix35",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6526),
                            DailyPrice = 70.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6544),
                            DailyPrice = 75.0,
                            FuelType = 1,
                            ModelYear = 2017,
                            Name = "Sonata",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6560),
                            DailyPrice = 55.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Cerato",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6711),
                            DailyPrice = 75.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Optima",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 7,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6729),
                            DailyPrice = 50.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Rio",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6751),
                            DailyPrice = 90.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Sorento",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 7,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6767),
                            DailyPrice = 65.0,
                            FuelType = 2,
                            ModelYear = 2014,
                            Name = "Sportage",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 9,
                            ColorId = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7151),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "LX570",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7168),
                            DailyPrice = 350.0,
                            FuelType = 1,
                            ModelYear = 2012,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 1,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7187),
                            DailyPrice = 400.0,
                            FuelType = 1,
                            ModelYear = 2015,
                            Name = "G-class",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7271),
                            DailyPrice = 350.0,
                            FuelType = 2,
                            ModelYear = 2016,
                            Name = "S-class",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 1,
                            ColorId = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7286),
                            DailyPrice = 450.0,
                            FuelType = 2,
                            ModelYear = 2016,
                            Name = "V-class",
                            PassengerCount = 6,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            ColorId = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7301),
                            DailyPrice = 80.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "L200",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7316),
                            DailyPrice = 85.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Pajero",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 5,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7331),
                            DailyPrice = 90.0,
                            FuelType = 2,
                            ModelYear = 2013,
                            Name = "Navara",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 5,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7347),
                            DailyPrice = 50.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Sunny",
                            PassengerCount = 5,
                            TransmissionType = 2,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7363),
                            DailyPrice = 90.0,
                            FuelType = 1,
                            ModelYear = 2013,
                            Name = "Camry",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7379),
                            DailyPrice = 160.0,
                            FuelType = 1,
                            ModelYear = 2014,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 3,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7395),
                            DailyPrice = 300.0,
                            FuelType = 1,
                            ModelYear = 2018,
                            Name = "Land Cruiser",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 4,
                            ColorId = 3,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7410),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2011,
                            Name = "X5",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 3,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7428),
                            DailyPrice = 200.0,
                            FuelType = 1,
                            ModelYear = 2018,
                            Name = "Prado",
                            PassengerCount = 7,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 10,
                            ColorId = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7444),
                            DailyPrice = 250.0,
                            FuelType = 4,
                            ModelYear = 2016,
                            Name = "X",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 10,
                            ColorId = 5,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7461),
                            DailyPrice = 270.0,
                            FuelType = 4,
                            ModelYear = 2018,
                            Name = "S",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 10,
                            ColorId = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7478),
                            DailyPrice = 250.0,
                            FuelType = 4,
                            ModelYear = 2017,
                            Name = "3",
                            PassengerCount = 4,
                            TransmissionType = 1,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 5,
                            ColorId = 6,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(7557),
                            DailyPrice = 70.0,
                            FuelType = 4,
                            ModelYear = 2017,
                            Name = "Leaf",
                            PassengerCount = 5,
                            TransmissionType = 1,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.CarImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("CarImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ImageUrl = "bmw-m5.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            ImageUrl = "toyota-prado-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            ImageUrl = "chevrolet-aveo-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            ImageUrl = "hyundai-accent-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            ImageUrl = "hyundai-azera-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            ImageUrl = "hyundai-elantra-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            ImageUrl = "hyundai-h1-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            ImageUrl = "hyundai-ix35-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            ImageUrl = "hyundai-sonata-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            ImageUrl = "hyundai-sonata-2017.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11,
                            ImageUrl = "kia-cerato-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12,
                            ImageUrl = "kia-optima-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13,
                            ImageUrl = "kia-rio-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14,
                            ImageUrl = "kia-sorento-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            CarId = 15,
                            ImageUrl = "kia-sportage-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            CarId = 16,
                            ImageUrl = "lexus-570-2012.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            CarId = 17,
                            ImageUrl = "mercedes-g-class-2012.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            CarId = 18,
                            ImageUrl = "mercedes-g-class-2015.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            CarId = 19,
                            ImageUrl = "mercedes-s-class-2016.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            CarId = 20,
                            ImageUrl = "mercedes-v-class-2016.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            CarId = 21,
                            ImageUrl = "mitsubishi-L200-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            CarId = 22,
                            ImageUrl = "mitsubishi-pajero.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            CarId = 23,
                            ImageUrl = "nissan-navara-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 24,
                            CarId = 24,
                            ImageUrl = "nissan-sunny-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 25,
                            CarId = 25,
                            ImageUrl = "toyota-camry-2013.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 26,
                            CarId = 26,
                            ImageUrl = "toyota-land-cruiser-2014.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 27,
                            CarId = 27,
                            ImageUrl = "toyota-land-cruiser-2018.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 28,
                            CarId = 28,
                            ImageUrl = "bmw-x5.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 29,
                            CarId = 29,
                            ImageUrl = "toyota-prado-2018.jpg",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 30,
                            CarId = 30,
                            ImageUrl = "tesla-x-2016.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 31,
                            CarId = 31,
                            ImageUrl = "tesla-s-2018.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 32,
                            CarId = 32,
                            ImageUrl = "tesla-3-2017.png",
                            IsMain = true,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 33,
                            CarId = 33,
                            ImageUrl = "nissan-leaf-2017.png",
                            IsMain = true,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6256),
                            Name = "Qara",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6277),
                            Name = "Ağ",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6293),
                            Name = "Qəhvəyi",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6309),
                            Name = "Boz",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6325),
                            Name = "Qırmızı",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(6344),
                            Name = "Mavi",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8280),
                            ImageUrl = "Arzu.jpg",
                            Name = "Arzu",
                            Position = "CEO",
                            Surname = "Mahmudov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8305),
                            ImageUrl = "Murad.jpg",
                            Name = "Murad",
                            Position = "CFO",
                            Surname = "Qarayev",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8325),
                            ImageUrl = "Riyad.jpg",
                            Name = "Riyad",
                            Position = "Developer",
                            Surname = "Nağıyev",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8342),
                            ImageUrl = "Pasha.jpg",
                            Name = "Paşa",
                            Position = "Mütəxəssis",
                            Surname = "Bayramov",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8358),
                            ImageUrl = "Maarif.jpg",
                            Name = "Maarif",
                            Position = "Mütəxəssis",
                            Surname = "Aliyev",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 3, 8, 1, 36, 27, 602, DateTimeKind.Local).AddTicks(8376),
                            ImageUrl = "Sahin.jpg",
                            Name = "Şahin",
                            Position = "Mütəxəssis",
                            Surname = "Cəbrayılov",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rent_a_Car_.Net.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Car", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rent_a_Car_.Net.Models.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.CarImage", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.Car", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Rental", b =>
                {
                    b.HasOne("Rent_a_Car_.Net.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rent_a_Car_.Net.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Car", b =>
                {
                    b.Navigation("CarImages");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Rent_a_Car_.Net.Models.Color", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
